require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'carData' do
  use_unimodules!(exclude: ['expo-app-loader-provider', 'expo-file-system', 'unimodules-barcode-scanner-interface', 'unimodules-camera-interface', 'unimodules-face-detector-interface', 'unimodules-sensors-interface', 'unimodules-task-manager-interface'])
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'carDataTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'carData-tvOS' do
  # Pods for carData-tvOS

  target 'carData-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
